name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the issue.
      placeholder: |
        1. Configure .env with ...
        2. Run npm start
        3. Send !schedule status
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs (redacted)
      description: Remove personal identifiers and secrets.
  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: 20.x
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: Ubuntu 22.04
    validations:
      required: true
